name: CD_main_checkout

on:
  push:
    branches:
      - main
    paths:
      - 'projects/checkout/**'

jobs:
  buildAngular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Angular Dependencies
        run: npm install
      - name: Build Angular
        run: npm run ng build --project checkout
      - name: Archive Angular Artifact
        uses: actions/upload-artifact@master
        with:
          name: checkoutAngular
          path: dist/checkout/
  deploy:
    name: Deploy
    needs: [buildAngular]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Angular Artifact
        uses: actions/download-artifact@master
        with:
          name: checkoutAngular
          path: dist/checkout/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:checkout
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
