name: CD_main_checkout

on:
  push:
    branches:
      - main
    paths:
      - 'projects/checkout/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm ng build --project checkout --configuration=production
      - name: Archive Production Artifact
        run: actions/upload-artifact@master
        with:
          name: dist/checkout
          path: dist/checkout
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist/checkout
          path: dist/checkout
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:checkout
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
