name: CD_main_checkout

on:
  push:
    branches:
      - main
    paths:
      - 'projects/checkout/**'

jobs:
  buildAngular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build Angular
        run: npm run ng build --project checkout --configuration=production
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: checkoutAngular
          path: dist/checkout/
  buildCloudFunction:
    name: Build Cloud Function
    needs: [buildAngular]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: functions
        run: npm install
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: checkoutAngular
          path: dist/checkout/
      - name: Build Cloud Function
        run: npm run build:functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: checkoutCloudFunction
          path: |
            functions/dist/
            functions/lib/
            functions/.eslintrc.js
  deploy:
    name: Deploy
    needs: [buildAngular, buildCloudFunction]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: checkoutAngular
          path: dist/checkout/
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: checkoutCloudFunction
          path: functions/
      - name: Install Dependencies
        working-directory: functions
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:checkout,functions:checkoutUniversal
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
