name: CD_main_experiences

on:
  push:
    branches:
      - main
    paths:
      - 'projects/experiences/**'

jobs:
  buildAngular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build Angular
        run: npm run build:ssr:experiences
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: experiencesAngular
          path: dist/experiences/
  buildCloudFunction:
    needs: [buildAngular]
    name: Build Cloud Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: experiencesAngular
          path: dist/experiences/
      - name: Build Cloud Function
        run: npm run build:functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: experiencesCloudFunction
          path: |
            functions/**
            !functions/node_modules
  deploy:
    name: Deploy
    needs: [buildAngular, buildCloudFunction]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: experiencesAngular
          path: dist/experiences/
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: experiencesCloudFunction
          path: functions/
      - name: Install Dependencies
        working-directory: ./functions
        run: npm install
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:experiences,functions:experiencesUniversal
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
