name: CD_main_account

on:
  push:
    branches:
      - main
    paths:
      - 'projects/account/**'
      - 'functions/src/features/account/**'

jobs:
  buildAngular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Angular Dependencies
        run: npm install
      - name: Build Angular
        run: npm run build:ssr:account
      - name: Archive Angular Artifact
        uses: actions/upload-artifact@master
        with:
          name: accountAngular
          path: dist/account/
  buildCloudFunction:
    needs: [buildAngular]
    name: Build Cloud Function
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Cloud Function Dependencies
        working-directory: ./functions
        run: npm install
      - name: Download Angular Artifact
        uses: actions/download-artifact@master
        with:
          name: accountAngular
          path: dist/account/
      - name: Create JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "serviceAccountKeys.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEYS }}
          dir: 'functions/src/'
      - name: Build Cloud Function
        run: npm run --prefix functions copy:account && npm run build:functions
      - name: Clean JSON
        run: |
          rm -f \
            functions/src/serviceAccountKeys.json \
            functions/lib/serviceAccountKeys.json
      - name: Archive Cloud Function Artifact
        uses: actions/upload-artifact@master
        with:
          name: accountCloudFunction
          path: |
            functions/**
            !functions/node_modules
  deploy:
    name: Deploy
    needs: [buildAngular, buildCloudFunction]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Angular Artifact
        uses: actions/download-artifact@master
        with:
          name: accountAngular
          path: dist/account/
      - name: Download Cloud Function Artifact
        uses: actions/download-artifact@master
        with:
          name: accountCloudFunction
          path: functions/
      - name: Install Cloud Function Dependencies
        working-directory: ./functions
        run: npm install
      - name: Create JSON
        id: create-json
        uses: jsdaniell/create-json@v1.2.2
        with:
          name: "serviceAccountKeys.json"
          json: ${{ secrets.SERVICE_ACCOUNT_KEYS }}
          dir: 'functions/src/'
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:account,functions:accountUniversal
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
