name: CD_main_experiences

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm ng build --project experiences --configuration=production
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist/experiences
          path: dist/experiences
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist/experiences
          path: dist/experiences
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:experiences
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
