name: CD_main_checkout

on:
  push:
    branches:
      - main
    paths:
      - 'projects/checkout/**'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build Angular
        run: npm run ng build --project checkout --configuration=production
      - name: Build Cloud Function
        run: npm run build:functions
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: checkout
          path: |
            dist/checkout/
            functions/dist/
            functions/lib/
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: checkout
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:checkout
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
