name: CD_main_account

on:
  push:
    branches:
      - main
    paths:
      - 'projects/account/**'

jobs:
  buildAngular:
    name: Build Angular
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Angular Dependencies
        run: npm install
      - name: Build Angular
        run: ng build --project account
      - name: Archive Angular Artifact
        uses: actions/upload-artifact@master
        with:
          name: accountAngular
          path: dist/account/
  deploy:
    name: Deploy
    needs: [buildAngular]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Angular Artifact
        uses: actions/download-artifact@master
        with:
          name: accountAngular
          path: dist/account/
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:account
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY_TO_POINT_ORG }}
